#!/bin/bash

[ -z "PS1" ] && trap "error_exit" 1 2 3 15 ERR 

PLAY_VERSION=2.1.3
MAVEN_VERSION=3.0.5
SBT_VERSION=0.12.4

PLAY_ARTIFACT=play-${PLAY_VERSION}
PLAY_HOME=~/.play/${PLAY_ARTIFACT}
PLAY_DOWNLOAD="http://downloads.typesafe.com/play/${PLAY_VERSION}/play-${PLAY_VERSION}.zip"
PLAY_TMP=/tmp/${PLAY_ARTIFACT}.zip

SBT_DOWNLOAD="http://scalasbt.artifactoryonline.com/scalasbt/sbt-native-packages/org/scala-sbt/sbt/${SBT_VERSION}/sbt.tgz"

function error_exit 
{
	echo "An error has happened, shutting down" 
	[ -f ./stop-all.sh ] && ./stop-all.sh
	exit 1
}

function flush_hmrc_code_from_play_cache 
{
	echo "Wiping HMRC code from play cache"
	rm -rf ${PLAY_HOME}/repository/cache/uk.gov.hmrc	
}

function flush_play_cache
{
	echo "Wiping play cache"
	rm -rf ${PLAY_HOME}/repository/cache
}

function echo_frontend_uris 
{
	echo
	echo "*********************************************************"
	echo "* Thank you for choosing to run the HMRC tax frontend!! *"
	echo "* We hope this code will bring you great success        *"
	echo "*********************************************************"
	echo
	echo "The frontend URI is:"
	echo
	echo "  http://localhost:9000"
	echo
	echo "And you can log in as:"
	echo
	echo "  jdensmore / password"
	echo "  jfisher   / password"
	echo 
	echo "If you want to edit the frontend templates you can find them in:"
	echo "  frontend/app/views/"
	echo
	echo
}

if [ ! -d ${PLAY_HOME} ] 
then
	rm -f $PLAY_TMP

	echo "No local play installation found in ${PLAY_HOME}"
	
	echo "Downloading ${PLAY_DOWNLOAD}"
	curl -o ${PLAY_TMP} "${PLAY_DOWNLOAD}"

	echo "Extracting play framework"
	mkdir -p ~/.play
	unzip ${PLAY_TMP} -d ~/.play
fi

MAVEN_DIR=~/.maven
MAVEN_ARTIFACT=apache-maven-${MAVEN_VERSION}
MAVEN_DOWNLOAD="http://alphagov.github.io/devutil/apache-maven-${MAVEN_VERSION}-bin.tar.gz"
MAVEN_TMP=/tmp/${MAVEN_ARTIFACT}.tar.gz

if [ ! -d ${MAVEN_DIR} ]
then
	mkdir -p ${MAVEN_DIR}
	echo "Downloading ${MAVEN_DOWNLOAD}"
	curl -o ${MAVEN_TMP} "${MAVEN_DOWNLOAD}"
	tar zxvf ${MAVEN_TMP} -C ${MAVEN_DIR}
fi

SBT_DIR=~/.sbt-jars
SBT_ARTIFACT=sbt-${SBT_VERSION}-launch.jar
SBT_TMP=/tmp/sbt-${SBT_VERSION}.tgz
SBT_FILE=${SBT_DIR}/${SBT_ARTIFACT}

if [ ! -f ${SBT_FILE} ]
then
	mkdir -p ${SBT_DIR}
	echo "Downloading ${SBT_DOWNLOAD}"
	curl -o ${SBT_TMP} "${SBT_DOWNLOAD}"
	rm -rf /tmp/sbt
	tar zxvf ${SBT_TMP} -C /tmp
	cp /tmp/sbt/bin/sbt-launch.jar ${SBT_FILE}
fi

export M2_HOME=${MAVEN_DIR}/${MAVEN_ARTIFACT}
export PATH=${M2_HOME}/bin:${PLAY_HOME}:${PATH}
